import { POI } from './types';

export const SEED_POIS: POI[] = [
  {
    id: 'poi_1',
    city: 'Sydney',
    name: 'Single O Surry Hills',
    category: 'cafe',
    lat: -33.8812,
    lng: 151.2093,
    price_tier: 1,
    estimated_cost: 15.0,
    rating: 4.8,
    vibe_tags: ['coffee', 'food', 'trendy', 'breakfast'],
    best_time: 'morning',
    description: 'Iconic Surry Hills coffee roaster renowned for reservoir espresso shots and innovative breakfast options.'
  },
  {
    id: 'poi_2',
    city: 'Sydney',
    name: 'Bondi to Coogee Coastal Walk',
    category: 'activity',
    lat: -33.8915,
    lng: 151.2767,
    price_tier: 1,
    estimated_cost: 0.0,
    rating: 4.9,
    vibe_tags: ['coastal', 'walk', 'nature', 'scenic', 'ocean'],
    best_time: 'afternoon',
    description: 'World-famous 6km cliffside walking trail connecting Bondi, Tamarama, Bronte, and Coogee beaches.'
  },
  {
    id: 'poi_3',
    city: 'Sydney',
    name: 'Sydney Opera House & Circular Quay',
    category: 'sight',
    lat: -33.8568,
    lng: 151.2153,
    price_tier: 2,
    estimated_cost: 25.0,
    rating: 4.9,
    vibe_tags: ['landmark', 'scenic', 'culture', 'architecture'],
    best_time: 'morning',
    description: 'UNESCO World Heritage masterpiece overlooking Sydney Harbour with guided architectural tours.'
  },
  {
    id: 'poi_4',
    city: 'Sydney',
    name: 'The Rocks Historic Quarter & Markets',
    category: 'activity',
    lat: -33.8598,
    lng: 151.2090,
    price_tier: 2,
    estimated_cost: 20.0,
    rating: 4.7,
    vibe_tags: ['market', 'food', 'history', 'walk', 'culture'],
    best_time: 'evening',
    description: 'Cobblestone laneways filled with artisan stalls, historic pubs, street food, and harbor views.'
  },
  {
    id: 'poi_5',
    city: 'Sydney',
    name: 'The Grounds of Alexandria',
    category: 'cafe',
    lat: -33.9108,
    lng: 151.1961,
    price_tier: 2,
    estimated_cost: 22.0,
    rating: 4.6,
    vibe_tags: ['coffee', 'food', 'garden', 'scenic'],
    best_time: 'morning',
    description: 'Lush garden oasis inside a 1920s industrial sanctuary featuring artisanal bakery and specialty coffee.'
  },
  {
    id: 'poi_6',
    city: 'Sydney',
    name: 'Royal Botanic Garden Sydney',
    category: 'sight',
    lat: -33.8642,
    lng: 151.2166,
    price_tier: 1,
    estimated_cost: 0.0,
    rating: 4.8,
    vibe_tags: ['nature', 'walk', 'scenic', 'park', 'relaxed'],
    best_time: 'afternoon',
    description: '30-hectare botanical garden adjacent to Circular Quay with panoramic harbor views and Mrs Macquarie’s Chair.'
  },
  {
    id: 'poi_7',
    city: 'Sydney',
    name: 'Barangaroo Reserve & Sunset Walk',
    category: 'sight',
    lat: -33.8601,
    lng: 151.2009,
    price_tier: 1,
    estimated_cost: 0.0,
    rating: 4.7,
    vibe_tags: ['scenic', 'sunset', 'walk', 'nature'],
    best_time: 'evening',
    description: 'Reclaimed headland park constructed from native sandstone blocks offering serene sunset vistas over Darling Harbour.'
  },
  {
    id: 'poi_8',
    city: 'Sydney',
    name: 'Manly Ferry & Shelly Beach Walk',
    category: 'activity',
    lat: -33.7997,
    lng: 151.2882,
    price_tier: 1,
    estimated_cost: 10.0,
    rating: 4.8,
    vibe_tags: ['coastal', 'ferry', 'beach', 'scenic', 'walk'],
    best_time: 'afternoon',
    description: 'Iconic 30-minute ferry journey across Sydney Harbour followed by a calm marine reserve promenade to Shelly Beach.'
  },
  {
    id: 'poi_9',
    city: 'Sydney',
    name: 'Celsius Coffee Co. Kirribilli',
    category: 'cafe',
    lat: -33.8488,
    lng: 151.2168,
    price_tier: 2,
    estimated_cost: 18.0,
    rating: 4.6,
    vibe_tags: ['coffee', 'harbor', 'view', 'scenic', 'breakfast'],
    best_time: 'morning',
    description: 'Floating café perched right on the Kirribilli ferry wharf serving pour-overs with unmatched Opera House backdrop.'
  },
  {
    id: 'poi_10',
    city: 'Sydney',
    name: 'Taronga Zoo Waterfront Promenade',
    category: 'activity',
    lat: -33.8434,
    lng: 151.2412,
    price_tier: 3,
    estimated_cost: 35.0,
    rating: 4.7,
    vibe_tags: ['nature', 'wildlife', 'view', 'scenic'],
    best_time: 'afternoon',
    description: 'Hillside wildlife sanctuary showcasing native Australian animals with spectacular skyline vistas.'
  },
  {
    id: 'poi_11',
    city: 'Sydney',
    name: 'Restaurant Hubert Underground',
    category: 'food',
    lat: -33.8650,
    lng: 151.2105,
    price_tier: 3,
    estimated_cost: 45.0,
    rating: 4.8,
    vibe_tags: ['food', 'dining', 'jazz', 'nightlife'],
    best_time: 'evening',
    description: 'Atmospheric subterranean French bistro featuring live jazz, candlelit wood paneling, and classic cuisine.'
  },
  {
    id: 'poi_12',
    city: 'Sydney',
    name: 'Coogee Pavilion Ocean Rooftop',
    category: 'food',
    lat: -33.9205,
    lng: 151.2583,
    price_tier: 2,
    estimated_cost: 30.0,
    rating: 4.6,
    vibe_tags: ['food', 'sunset', 'ocean', 'scenic', 'nightlife'],
    best_time: 'evening',
    description: 'Multi-level coastal dining hub with a Mediterranean-inspired rooftop bar overlooking Coogee Bay.'
  },
  {
    id: 'poi_13',
    city: 'Sydney',
    name: 'Art Gallery of New South Wales',
    category: 'sight',
    lat: -33.8688,
    lng: 151.2173,
    price_tier: 1,
    estimated_cost: 0.0,
    rating: 4.7,
    vibe_tags: ['art', 'culture', 'museum', 'relaxed'],
    best_time: 'afternoon',
    description: 'Premier public art museum featuring extensive Indigenous Australian collections and the revolutionary Sydney Modern pavilion.'
  },
  {
    id: 'poi_14',
    city: 'Sydney',
    name: 'Edition Roasters Haymarket',
    category: 'cafe',
    lat: -33.8789,
    lng: 151.2045,
    price_tier: 2,
    estimated_cost: 16.0,
    rating: 4.7,
    vibe_tags: ['coffee', 'Japanese', 'food', 'trendy'],
    best_time: 'morning',
    description: 'Japanese-Nordic fusion coffee house featuring single-origin filter coffees and charcoal fluffy pancakes.'
  },
  {
    id: 'poi_15',
    city: 'Sydney',
    name: 'Mr Wong Cantonese Dining',
    category: 'food',
    lat: -33.8637,
    lng: 151.2078,
    price_tier: 3,
    estimated_cost: 40.0,
    rating: 4.7,
    vibe_tags: ['food', 'dining', 'culture'],
    best_time: 'evening',
    description: 'Grand 240-seat Cantonese eatery tucked in Bridge Lane famous for dim sum, roasted duck, and cocktail craft.'
  },
  {
    id: 'poi_16',
    city: 'Sydney',
    name: 'Watsons Bay & Camp Cove Walk',
    category: 'activity',
    lat: -33.8427,
    lng: 151.2829,
    price_tier: 1,
    estimated_cost: 8.0,
    rating: 4.8,
    vibe_tags: ['coastal', 'walk', 'beach', 'scenic'],
    best_time: 'afternoon',
    description: 'Historic harbor village with quiet sandy coves, seafood shacks, and dramatic South Head lighthouse walk.'
  },
  {
    id: 'poi_17',
    city: 'Sydney',
    name: 'Mary’s Newtown Burger Bar',
    category: 'food',
    lat: -33.8958,
    lng: 151.1798,
    price_tier: 1,
    estimated_cost: 18.0,
    rating: 4.6,
    vibe_tags: ['food', 'casual', 'nightlife'],
    best_time: 'evening',
    description: 'Cult-favorite inner-west rock bar renowned for juicy burgers, fried chicken, and energetic indie vinyl soundtrack.'
  },
  {
    id: 'poi_18',
    city: 'Sydney',
    name: 'Room 10 Espresso Potts Point',
    category: 'cafe',
    lat: -33.8722,
    lng: 151.2256,
    price_tier: 1,
    estimated_cost: 14.0,
    rating: 4.8,
    vibe_tags: ['coffee', 'local', 'food', 'breakfast'],
    best_time: 'morning',
    description: 'Tucked in Llankelly Place laneway, serving legendary espresso and breakfast melt sandwiches.'
  },
  {
    id: 'poi_19',
    city: 'Sydney',
    name: 'Observatory Hill Park Sunset View',
    category: 'sight',
    lat: -33.8592,
    lng: 151.2049,
    price_tier: 1,
    estimated_cost: 0.0,
    rating: 4.9,
    vibe_tags: ['sunset', 'picnic', 'view', 'scenic', 'romantic'],
    best_time: 'evening',
    description: 'Grassy hilltop park overlooking Sydney Harbour Bridge offering unmatched golden hour views.'
  },
  {
    id: 'poi_20',
    city: 'Sydney',
    name: 'Spit to Manly Coastal Track',
    category: 'activity',
    lat: -33.8050,
    lng: 151.2510,
    price_tier: 1,
    estimated_cost: 0.0,
    rating: 4.9,
    vibe_tags: ['coastal', 'walk', 'nature', 'scenic', 'hiking'],
    best_time: 'afternoon',
    description: '10km bushwalking track winding past secluded beaches, Aboriginal rock engravings, and dramatic coastal bluffs.'
  }
];
